---
env:
  browser: true
  node: true
extends:
  - eslint-config-airbnb-base
  - 'plugin:@typescript-eslint/recommended'
  - prettier/@typescript-eslint
  - 'plugin:prettier/recommended'
  - 'plugin:sonarjs/recommended'
overrides:
  - env:
      mocha: true
    files:
      - '*.test.ts'
      - 'testSdk.ts'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 11
  sourceType: module
plugins:
  - eslint-plugin-tsdoc
  - prettier
  - sonarjs
  - markdown
rules:
  '@typescript-eslint/no-var-requires': off
  complexity:
    - warn
    - max: 5
  import/extensions:
    - warn
    - .ts: ignorePackages
  import/no-extraneous-dependencies: off
  import/prefer-default-export: off
  linebreak-style: off
  max-classes-per-file: off
  no-confusing-arrow: off
  no-multiple-empty-lines: error
  no-unused-vars:
    - warn
    - argsIgnorePattern: ^_
  prettier/prettier:
    - error
    - arrowParens: always
      printWidth: 120
      singleQuote: true
      trailingComma: all
    - usePrettierrc: false
  quotes:
    - error
    - single
  semi:
    - error
    - always
  sort-imports:
    - error
    - ignoreDeclarationSort: true
  tsdoc/syntax: warn
settings:
  import/resolver:
    node:
      extensions:
        - .js
        - .ts
        - .md
