
---
branches: 100
checkCoverage: true
extension:
  - .ts
functions: 100
include:
  - src/**/*.ts
instrument: true
lines: 100
reporter:
  - html
  - text-summary
  - text
require:
  - source-map-support/register
  - ts-node/register
sourceMap: true
statements: 100
watermarks:
  - lines: [80, 95]
  - functions: [80, 95]
  - branches: [80, 95]
  - statements: [80, 95]
