executors:
  nodeaws-executor:
    docker:
      - image: ns8inc/nodeaws:node-erbium
jobs:
  deploy:
    executor: nodeaws-executor
    steps:
      - add_ssh_keys:
          fingerprints:
            - "52:a4:0f:d8:26:b8:3a:ae:23:55:94:2e:d5:3c:b5:08"
      - checkout
      - run:
          command: |
            git config user.email noreply@ns8.com
            git config user.name 'CircleCI'
          name: Setup Git
      - run:
          command: |
            yarn config set version-tag-prefix ''
            current_version="$(jq -r .version package.json)"

            while
              new_version="$(jq -r .version package.json)"
              [[ "$(git tag | grep -c $new_version)" -gt "0" ]]
            do yarn version --no-git-tag-version --patch; done

            if [ "$new_version" = "$current_version" ]; then
              # Someone manually bumped the version in package.json, so don't bump, only tag.
              git tag $new_version
            else
              # Reset then bump and tag like usual.
              git checkout package.json
              yarn version --new-version $new_version
            fi
          name: Bump Version
      - run:
          command: |
            if ! git push -u origin master --tags; then
              echo "Push failed. Please add this CircleCI deploy key to your repo with write access:"
              ssh-keygen -y -f ~/.ssh/id_rsa
              exit 1
            fi
          name: Tag Release in GitHub
  publish:
    executor: nodeaws-executor
    steps:
      - checkout
      - run:
          command: |
            git config user.email noreply@ns8.com
            git config user.name 'CircleCI'
          name: Setup Git
      - run:
          command: echo "//registry.npmjs.org/:_authToken=${NS8_GLOBAL_NPM_TOKEN}" > ~/.npmrc
          name: Configure NPM
      - run:
          command: |
            yarn set version berry
            yarn install
          name: Install Dependencies
      - run:
          command: yarn build:prod
          name: Build
      - run:
          command: |
            version=$(jq -r .version package.json)
            echo "export VERSION=$version" >> $BASH_ENV
          name: Get Version
      - run:
          command: |
            yarn gren release -m -t $VERSION -T $GITHUB_ACCESS_TOKEN
            yarn gren release -o -t $VERSION -T $GITHUB_ACCESS_TOKEN
          name: Create GitHub Release
      - run:
          command: yarn docs:publish
          name: Publish API Documentation
      - run:
          command: npm publish
          name: Publish
  test:
    executor: nodeaws-executor
    steps:
      - checkout
      - run:
          command: echo "//registry.npmjs.org/:_authToken=${NS8_GLOBAL_NPM_TOKEN}" > ~/.npmrc
          name: Configure NPM
      - run:
          command: |
            yarn set version berry
            yarn install
          name: Install Dependencies
      - run:
          command: yarn lint
          name: Lint
      - run:
          command: yarn test
          name: Run Tests
version: 2.1
workflows:
  publish:
    jobs:
      - publish:
          context: org-global
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
  test_and_deploy:
    jobs:
      - test:
          context: org-global
          filters:
            branches:
              ignore: gh-pages
      - approve:
          context: org-global
          filters:
            branches:
              only: master
          requires:
            - test
          type: approval
      - deploy:
          context: org-global
          filters:
            branches:
              only: master
          requires:
            - approve
